# Generated by Django 3.2 on 2023-04-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0002_auto_20230409_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
