# Generated by Django 3.2.18 on 2024-02-10 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_generation', '0003_skill_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('YTB', 'Youtube'), ('FILE', 'File)'), ('TEXT', 'Text')], max_length=10)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('CREATED', 'Created'), ('PROCESSING', 'Processing')], max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memories',
            },
        ),
    ]
