# Generated by Django 3.2 on 2023-04-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='payload',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='output',
            name='skill_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='content_generation.skill'),
        ),
    ]
