# Generated by Django 3.2 on 2023-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0004_auto_20230409_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='payload',
            field=models.JSONField(blank=True),
        ),
    ]
