# Generated by Django 3.2.18 on 2024-02-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0005_auto_20240210_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('CREATED', 'Created'), ('PROCESSING', 'Processing')], default='CREATED', max_length=10),
        ),
    ]
