# Generated by Django 3.2 on 2023-04-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0007_alter_output_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='skill_id',
            new_name='skill',
        ),
    ]
