# Generated by Django 3.2 on 2023-04-10 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0008_rename_skill_id_output_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('delta', models.JSONField()),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('isPublic', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
