# Generated by Django 3.2 on 2023-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0009_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='delta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
