# Generated by Django 3.2.18 on 2024-04-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0009_auto_20240405_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('CREATED', 'Created')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('YTB', 'Youtube'), ('FILE', 'File')], max_length=10),
        ),
    ]
