# Generated by Django 3.2 on 2023-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0010_alter_document_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
