# Generated by Django 3.2.18 on 2024-04-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0011_auto_20240405_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('CREATED', 'Created'), ('PROCESSED', 'Processed')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('FILE', 'File'), ('TEXT', 'Text'), ('YTB', 'Youtube')], max_length=10),
        ),
    ]
