# Generated by Django 3.2 on 2023-04-11 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0011_alter_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='-')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content_generation.project'),
            preserve_default=False,
        ),
    ]
