# Generated by Django 3.2 on 2023-04-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0002_suggestion_status'),
        ('content_generation', '0012_auto_20230411_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='suggestion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywordresearch.suggestion'),
        ),
    ]
