# Generated by Django 3.2.18 on 2024-01-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '__first__'),
        ('content_generation', '0013_document_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='e3e03983-bf5c-4c52-8ad8-c0f809cb353c', on_delete=django.db.models.deletion.CASCADE, to='app_auth.user', to_field='_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='e3e03983-bf5c-4c52-8ad8-c0f809cb353c', on_delete=django.db.models.deletion.CASCADE, to='app_auth.user', to_field='_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='e3e03983-bf5c-4c52-8ad8-c0f809cb353c', on_delete=django.db.models.deletion.CASCADE, to='app_auth.user', to_field='_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='e3e03983-bf5c-4c52-8ad8-c0f809cb353c', on_delete=django.db.models.deletion.CASCADE, to='app_auth.user', to_field='_id'),
            preserve_default=False,
        ),
    ]
