# Generated by Django 3.2 on 2023-04-01 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_keyword', models.CharField(max_length=255)),
                ('search_query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Suggestions',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serps', models.JSONField(default=dict)),
                ('questions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_suggestion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keywordresearch.suggestion')),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_search_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keywordresearch.search')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
