# Generated by Django 3.2.18 on 2024-01-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='suggestion',
            new_name='suggestions',
        ),
    ]
