# Generated by Django 3.2.18 on 2024-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0002_rename_suggestion_keywords_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
