# Generated by Django 3.2 on 2023-04-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0013_document_suggestion'),
        ('keywordresearch', '0002_suggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='project',
            field=models.ForeignKey(default='b6c69fbe-8a16-446e-b325-6c795de43dd5', on_delete=django.db.models.deletion.CASCADE, to='content_generation.project'),
            preserve_default=False,
        ),
    ]
