# Generated by Django 3.2.18 on 2023-11-25 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0003_suggestion_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embeddings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
            },
        ),
    ]
