# Generated by Django 3.2.18 on 2023-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0004_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='title',
            field=models.CharField(default='Keywords List', max_length=255),
        ),
    ]
