# Generated by Django 3.2.18 on 2023-11-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0005_keywords_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='saved_cluster',
            field=models.JSONField(default=dict),
        ),
    ]
