# Generated by Django 3.2.18 on 2023-11-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0006_keywords_saved_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='suggestion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywordresearch.suggestion'),
        ),
    ]
