# Generated by Django 3.2.18 on 2024-01-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0007_keywords_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='embeddings',
        ),
        migrations.AddField(
            model_name='keywords',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='keywords',
            name='suggestion',
            field=models.ManyToManyField(default=None, null=True, to='keywordresearch.Suggestion'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='search_query',
            field=models.CharField(default='', max_length=255),
        ),
    ]
